### ISSUE TITLE
use ISO dates in meeting minute titles

### ISSUE THREAD

**Issue by alexkrolick** [OpenSourceCornell/Meeting-Summaries#2]

**Comment by pniedzielski** [comment]
+1. I approve.

-----Original Message-----

**Comment by derekchiang** [comment]
LOL

**Comment by ghost** [comment]
Done, lol.

**Comment by derekchiang** [comment]
LOL.  This is good in the long run, but it does mean that all the links I sent out are now broken.  I should have done it this way: https://help.github.com/articles/getting-permanent-links-to-files/

**Comment by ghost** [comment]
Ah, sorry!! I didn't think about that, I should've asked. Well, hopefully people see what is going on, I guess if it was going to be done might as well now :/

**Comment by derekchiang** [comment]
Yeah you are absolutely right, might as well do it now.

**Comment by ghost** [comment]
Kk phewph ^_^
